### ISSUE TITLE
RuntimeError: storage has wrong size: expected 67123990 got 1024

### ISSUE THREAD

**Issue by NmomoN** [roytseng-tw/Detectron.pytorch#107]
When I run "**python tools/train_net_step.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml --use_tfboard --bs 16 --nw 4**"

I meet error about torch.load()
**INFO train_net_step.py: 234: Takes 124.40 sec(s) to construct roidb
Traceback (most recent call last):
  File "tools/train_net_step.py", line 454, in <module>
    main()
  File "tools/train_net_step.py", line 256, in main
    maskRCNN = Generalized_RCNN()
  File "/home/detection/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 124, in __init__
    self._init_modules()
  File "/home/detection/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 128, in _init_modules
    resnet_utils.load_pretrained_imagenet_weights(self)
  File "/home/detection/mask-rcnn.pytorch/lib/utils/resnet_weights_helper.py", line 29, in load_pretrained_imagenet_weights
    pretrianed_state_dict = convert_state_dict(torch.load(weights_file))
  File "/home/anaconda2/envs/tf/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/anaconda2/envs/tf/lib/python3.6/site-packages/torch/serialization.py", line 427, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: storage has wrong size: expected 67123990 got 1024**
So ,how can I solve it
Thank you very much

**Comment by alphadl** [comment]
have you fixed this bug right now? I encountered this error as you~
