### ISSUE TITLE
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by zhanghanbin3159** [roytseng-tw/Detectron.pytorch#117]
Traceback (most recent call last):
  File "tools/train_net_step.py", line 454, in <module>
    main()
  File "tools/train_net_step.py", line 350, in main
    blob = {'cfg': yaml.dump(cfg), 'args': args}
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 26, in represent
    node = self.represent_data(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 51, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 352, in represent_object
    return self.represent_mapping(tag+function_name, value)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 203, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 116, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 33, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 135, in ignore_aliases
    if data in [None, ()]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

shell:python3 tools/train_net_step.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_X-101-32x8d-FPN_1x.yaml --use_tfboard 

ubuntu 16.04
python 3.5
pytorch 0.4
cuda9
numpy 1.15

**Comment by zhanghanbin3159** [comment]
the version of pyyaml is too old, update the latest version
