### ISSUE TITLE
ImportError: dynamic module does not define init function (init_roi_pooling)

### ISSUE THREAD

**Issue by softmicro929** [roytseng-tw/Detectron.pytorch#156]
have you anyone got such a problem? when run testing.
Traceback (most recent call last):
  File "tools/test_net.py", line 14, in <module>
    from core.test_engine import run_inference
  File "/home/wangshuainan/mask-rcnn.pytorch/lib/core/test_engine.py", line 39, in <module>
    from modeling import model_builder
  File "/home/wangshuainan/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 11, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/home/wangshuainan/mask-rcnn.pytorch/lib/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/home/wangshuainan/mask-rcnn.pytorch/lib/model/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
**ImportError: dynamic module does not define init function (init_roi_pooling)**

**Comment by softmicro929** [comment]
make again.
