### ISSUE TITLE
Execution ‘sh make.sh’ command failed

### ISSUE THREAD

**Issue by 897051629** [roytseng-tw/Detectron.pytorch#166]
running build_ext
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/utils
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/numpy/core/include -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c utils/cython_bbox.c -o build/temp.linux-x86_64-2.7/utils/cython_bbox.o -Wno-cpp
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/utils
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed build/temp.linux-x86_64-2.7/utils/cython_bbox.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/utils/cython_bbox.so
building 'utils.cython_nms' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/numpy/core/include -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c utils/cython_nms.c -o build/temp.linux-x86_64-2.7/utils/cython_nms.o -Wno-cpp
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed build/temp.linux-x86_64-2.7/utils/cython_nms.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/utils/cython_nms.so
copying build/lib.linux-x86_64-2.7/utils/cython_bbox.so -> utils
copying build/lib.linux-x86_64-2.7/utils/cython_nms.so -> utils
Compiling nms kernels by nvcc...
make.sh: 20: make.sh: nvcc: not found
/home/xuebo/project/Detectron/lib/model/nms
['/home/xuebo/project/Detectron/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpFJkQ7j/_nms.c
setting the current directory to '/tmp/tmpFJkQ7j'
running build_ext
building '_nms' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c _nms.c -o ./_nms.o -std=c99
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed ./_nms.o /home/xuebo/project/Detectron/lib/model/nms/src/nms_cuda_kernel.cu.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o ./_nms.so
gcc: error: /home/xuebo/project/Detectron/lib/model/nms/src/nms_cuda_kernel.cu.o: 没有那个文件或目录
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
make.sh: 30: make.sh: nvcc: not found
/home/xuebo/project/Detectron/lib/model/roi_pooling
generating /tmp/tmpN1WwiB/_roi_pooling.c
setting the current directory to '/tmp/tmpN1WwiB'
running build_ext
building '_roi_pooling' extension
creating home
creating home/xuebo
creating home/xuebo/project
creating home/xuebo/project/Detectron
creating home/xuebo/project/Detectron/lib
creating home/xuebo/project/Detectron/lib/model
creating home/xuebo/project/Detectron/lib/model/roi_pooling
creating home/xuebo/project/Detectron/lib/model/roi_pooling/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c /home/xuebo/project/Detectron/lib/model/roi_pooling/src/roi_pooling.c -o ./home/xuebo/project/Detectron/lib/model/roi_pooling/src/roi_pooling.o -std=c99
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed ./_roi_pooling.o ./home/xuebo/project/Detectron/lib/model/roi_pooling/src/roi_pooling.o /home/xuebo/project/Detectron/lib/model/roi_pooling/src/roi_pooling.cu.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o ./_roi_pooling.so
gcc: error: /home/xuebo/project/Detectron/lib/model/roi_pooling/src/roi_pooling.cu.o: 没有那个文件或目录
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
make.sh: 48: make.sh: nvcc: not found
/home/xuebo/project/Detectron/lib/model/roi_crop
generating /tmp/tmpm5AIvv/_roi_crop.c
setting the current directory to '/tmp/tmpm5AIvv'
running build_ext
building '_roi_crop' extension
creating home
creating home/xuebo
creating home/xuebo/project
creating home/xuebo/project/Detectron
creating home/xuebo/project/Detectron/lib
creating home/xuebo/project/Detectron/lib/model
creating home/xuebo/project/Detectron/lib/model/roi_crop
creating home/xuebo/project/Detectron/lib/model/roi_crop/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o -std=c99
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c /home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c -o ./home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.o -std=c99
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBHWD_updateGradInput’:
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:190:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:189:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:188:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:187:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:186:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBCHW_updateGradInput’:
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:440:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:439:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:438:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:437:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.c:436:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed ./_roi_crop.o ./home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop.o /home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o ./_roi_crop.so
gcc: error: /home/xuebo/project/Detectron/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o: 没有那个文件或目录
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
make.sh: 57: make.sh: nvcc: not found
/home/xuebo/project/Detectron/lib/modeling/roi_xfrom/roi_align
generating /tmp/tmpfjbIQw/_roi_align.c
setting the current directory to '/tmp/tmpfjbIQw'
running build_ext
building '_roi_align' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/xuebo/miniconda3/envs/Dete/include/python2.7 -c _roi_align.c -o ./_roi_align.o -std=c99
gcc -pthread -shared -L/home/xuebo/miniconda3/envs/Dete/lib -Wl,-rpath=/home/xuebo/miniconda3/envs/Dete/lib,--no-as-needed ./_roi_align.o /home/xuebo/project/Detectron/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o -L/home/xuebo/miniconda3/envs/Dete/lib -lpython2.7 -o ./_roi_align.so
gcc: error: /home/xuebo/project/Detectron/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o: 没有那个文件或目录
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/xuebo/miniconda3/envs/Dete/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by 897051629** [comment]
gcc: error: /home/xuebo/project/Detectron/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o: No such directory
