### ISSUE TITLE
sh make.sh errors under pytorch version '1.0'.

### ISSUE THREAD

**Issue by youngwanLEE** [roytseng-tw/Detectron.pytorch#171]
### System information

* Operating system: Ubuntu 18.04
* CUDA version:  CUDA v10
* cuDNN version: cuDNN v7.3
* GPU models (for all devices if they are not all the same): ? V100
* python version: ? 3.6
* pytorch version: ? 1.0

Under pytorch '1.0', 

`sh make.sh
`

> Compiling nms kernels by nvcc...
> Traceback (most recent call last):
>   File "build.py", line 4, in <module>
>     from torch.utils.ffi import create_extension
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> 

This is because ffi was deprecated in Pytorch '1.0'. 

Could anyone solve this problem?

**Comment by wangg12** [comment]
I have the same problem. @roytseng-tw Do you have a plan to support pytorch 1.0?

**Comment by SanjunLiu** [comment]
I have the same problem .....

**Comment by louxy126** [comment]
the same problem， I use “pip install torch==0.4” instead of ”pip install torch“”。
then， pip install cffi
and sh make.sh ，it seems worked well

**Comment by 4ever-Rain** [comment]
I have the same problem when I use the pytorch 1.0.0.

**Comment by 1329844541** [comment]
I have met same trouble,too.Anyone have way?

**Comment by 1329844541** [comment]
I have met same trouble,too.Anyone have way?

**Comment by zymale** [comment]
I have met same trouble when I use the pytorch 1.0.0..Anyone have way?

**Comment by lamia482** [comment]
upload instruction on building for pytorch1.0
view the file in Markdown Editor
[https://drive.google.com/file/d/1aBGzUgMmCxb8OY0BQ0uCt7PCRvf7CS62/view?usp=sharing](url)

**Comment by FalkTannhaeuser** [comment]
There is a fork that seems to support PyTorch 1.0: https://github.com/adityaarun1/Detectron.pytorch
I have not yet tested it...
