### ISSUE TITLE
gcc: error trying to exec 'cc1': execvp: No such file or directory

### ISSUE THREAD

**Issue by tianmaliuixing** [roytseng-tw/Detectron.pytorch#173]
(python3) mike@amax:/data2/mike/Detectron.pytorch/lib$ sh make.sh
running build_ext
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/utils
gcc -pthread -B /home/mike/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/numpy/core/include -I/home/mike/anaconda3/envs/python3/include/python3.6m -c utils/cython_bbox.c -o build/temp.linux-x86_64-3.6/utils/cython_bbox.o -Wno-cpp
gcc: error trying to exec 'cc1': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
Compiling nms kernels by nvcc...
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Including CUDA code.
/data2/mike/Detectron.pytorch/lib/model/nms
['/data2/mike/Detectron.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/user/1003/tmpfre47qs9/_nms.c
running build_ext
building '_nms' extension
creating data2
creating data2/mike
creating data2/mike/Detectron.pytorch
creating data2/mike/Detectron.pytorch/lib
creating data2/mike/Detectron.pytorch/lib/model
creating data2/mike/Detectron.pytorch/lib/model/nms
creating data2/mike/Detectron.pytorch/lib/model/nms/src
gcc -pthread -B /home/mike/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/mike/anaconda3/envs/python3/include/python3.6m -c _nms.c -o ./_nms.o -std=c99
gcc: error trying to exec 'cc1': execvp: No such file or directory
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Including CUDA code.
/data2/mike/Detectron.pytorch/lib/model/roi_pooling
generating /tmp/user/1003/tmpqldme772/_roi_pooling.c
running build_ext
building '_roi_pooling' extension
creating data2
creating data2/mike
creating data2/mike/Detectron.pytorch
creating data2/mike/Detectron.pytorch/lib
creating data2/mike/Detectron.pytorch/lib/model
creating data2/mike/Detectron.pytorch/lib/model/roi_pooling
creating data2/mike/Detectron.pytorch/lib/model/roi_pooling/src
gcc -pthread -B /home/mike/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/mike/anaconda3/envs/python3/include/python3.6m -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
gcc: error trying to exec 'cc1': execvp: No such file or directory
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Including CUDA code.
/data2/mike/Detectron.pytorch/lib/model/roi_crop
generating /tmp/user/1003/tmpbwans0u6/_roi_crop.c
running build_ext
building '_roi_crop' extension
creating data2
creating data2/mike
creating data2/mike/Detectron.pytorch
creating data2/mike/Detectron.pytorch/lib
creating data2/mike/Detectron.pytorch/lib/model
creating data2/mike/Detectron.pytorch/lib/model/roi_crop
creating data2/mike/Detectron.pytorch/lib/model/roi_crop/src
gcc -pthread -B /home/mike/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/mike/anaconda3/envs/python3/include/python3.6m -c _roi_crop.c -o ./_roi_crop.o -std=c99
gcc: error trying to exec 'cc1': execvp: No such file or directory
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Including CUDA code.
/data2/mike/Detectron.pytorch/lib/modeling/roi_xfrom/roi_align
generating /tmp/user/1003/tmp_ix521me/_roi_align.c
running build_ext
building '_roi_align' extension
creating data2
creating data2/mike
creating data2/mike/Detectron.pytorch
creating data2/mike/Detectron.pytorch/lib
creating data2/mike/Detectron.pytorch/lib/modeling
creating data2/mike/Detectron.pytorch/lib/modeling/roi_xfrom
creating data2/mike/Detectron.pytorch/lib/modeling/roi_xfrom/roi_align
creating data2/mike/Detectron.pytorch/lib/modeling/roi_xfrom/roi_align/src
gcc -pthread -B /home/mike/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/mike/anaconda3/envs/python3/include/python3.6m -c _roi_align.c -o ./_roi_align.o -std=c99
gcc: error trying to exec 'cc1': execvp: No such file or directory
Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mike/anaconda3/envs/python3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by AlanStark** [comment]
I have this kind of issue too. 
My gcc verison is 6.4. and PyTorch version is 0.4.
