### ISSUE TITLE
AssertionError: Range subprocess failed (exit code: 1)

### ISSUE THREAD

**Issue by chelixuan** [roytseng-tw/Detectron.pytorch#174]
The command that I ran
python tools/test_net.py --dataset coco2017 --cfg configs/panet/e2e_panet_R-50-FPN_2x_mask.yaml --multi-gpu-testing --load_ckpt /home1/chelixuan/PANet_old/Outputs/e2e_panet_R-50-FPN_2x_mask/Oct31-19-45-45_2x1080Ti-36_step/ckpt/model_step17999

-------------------------------------------------------------------------------------------------------------------------------------------
problem:
loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
INFO test_engine.py: 330: loading checkpoint /home1/chelixuan/PANet_old/Outputs/e2e_panet_R-50-FPN_2x_mask/Oct31-19-45-45_2x1080Ti-36_step/ckpt/model_step179999.pth
Traceback (most recent call last):
  File "/home1/chelixuan/PANet_old/tools/test_net.py", line 112, in <module>
    check_expected_results=True)
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 125, in result_getter
    gpu_id=gpu_id
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 232, in test_net
    model = initialize_model_from_cfg(args, gpu_id=gpu_id)
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 332, in initialize_model_from_cfg
    net_utils.load_ckpt(model, checkpoint['model'])
  File "/home1/chelixuan/PANet_old/lib/utils/net.py", line 160, in load_ckpt
    for name in ckpt:
TypeError: 'Generalized_RCNN' object is not iterable
Traceback (most recent call last):
  File "tools/test_net.py", line 112, in <module>
    check_expected_results=True)
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 154, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, output_dir
  File "/home1/chelixuan/PANet_old/lib/core/test_engine.py", line 186, in multi_gpu_test_net_on_dataset
    args.load_ckpt, args.load_detectron, opts
  File "/home1/chelixuan/PANet_old/lib/utils/subprocess.py", line 108, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home1/chelixuan/PANet_old/lib/utils/subprocess.py", line 146, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)

---------------------------------------------------------------------------------------------------------------------------------------
### System information

* Operating system: ubuntu 14.04
* CUDA version: 8.0
* cuDNN version: 6.0
* python version: 3.6
* pytorch version: 0.4.0

**Comment by yyyyojiro** [comment]
have you solved it? I also have this problem..

**Comment by azhuantou** [comment]
I also have this problem.

**Comment by yyyyojiro** [comment]
In fact, I still don’t understand what caused this problem. But I guess it may be caused by multiple GPUs,&nbsp;
So I changed the tested GPU from four to one, then run successfully.&nbsp;
Hope this can help you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "roytseng-tw/Detectron.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 上午9:43
收件人:&nbsp;"roytseng-tw/Detectron.pytorch"<Detectron.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"only_Yojiro"<2402068371@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [roytseng-tw/Detectron.pytorch] AssertionError: Range subprocess failed (exit code: 1) (#174)





 
I also have this problem.
