### ISSUE TITLE
torch.utils.ffi is deprecated with pytorch 0.4.1

### ISSUE THREAD

**Issue by matchumen** [roytseng-tw/Detectron.pytorch#202]
When I run tools/test_net.py, I end up with ImportError even though I'm using PyTorch 0.4.1.

Traceback (most recent call last):
  File "tools/test_net.py", line 14, in <module>
    from core.test_engine import run_inference # tady to padá pro pána jána
  File "/home/matchumen/quest/detectors/mask-rcnn.pytorch/lib/core/test_engine.py", line 39, in <module>
    from modeling import model_builder
  File "/home/matchumen/quest/detectors/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 11, in <module>
    from model.roi_pooling.functions.roi_pool import RoIPoolFunction
  File "/home/matchumen/quest/detectors/mask-rcnn.pytorch/lib/model/roi_pooling/functions/roi_pool.py", line 3, in <module>
    from .._ext import roi_pooling
  File "/home/matchumen/quest/detectors/mask-rcnn.pytorch/lib/model/roi_pooling/_ext/roi_pooling/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/matchumen/.local/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### System information

* Operating system: Ubuntu 18.04
* CUDA version: 10.0
* GPU model: GTX 1050
* python version: 3.6
* pytorch version: 0.4.1

**Comment by matchumen** [comment]
Ubuntu apparentely

**Comment by matchumen** [comment]
My fault. Python executable pointed to '.local' directory, which contained PyTorch 1.0 for some reason.
