### ISSUE TITLE
error when training with my own coco-type data

### ISSUE THREAD

**Issue by HarrisXia** [roytseng-tw/Detectron.pytorch#205]
(pytorch) xia@Xia-Ubuntu:~/1-huafei/tianchi/xbu/Detectron.pytorch$ python tools/train_net_step.py --cfg experiments/e2e_faster_rcnn_X-101-64x4d-FPN_2x.yaml --dataset coco2014 --use_tfboard
Called with args:
Namespace(batch_size=None, cfg_file='experiments/e2e_faster_rcnn_X-101-64x4d-FPN_2x.yaml', cuda=True, dataset='coco2014', disp_interval=20, iter_size=1, load_ckpt=None, load_detectron=None, lr=None, lr_decay_gamma=None, no_save=False, num_workers=None, optimizer=None, resume=False, set_cfgs=[], start_step=0, use_tfboard=True)
effective_batch_size = batch_size * iter_size = 1 * 1
Adaptive config changes:
    effective_batch_size: 1 --> 1
    NUM_GPUS:             1 --> 1
    IMS_PER_BATCH:        1 --> 1
Adjust BASE_LR linearly according to batch_size change:
    BASE_LR: 0.01 --> 0.01
Adjust SOLVER.STEPS and SOLVER.MAX_ITER linearly based on effective_batch_size change:
    SOLVER.STEPS: [0, 120000, 180000, 240000] --> [0, 120000, 180000, 240000]
    SOLVER.MAX_ITER: 360000 --> 360000
Scale FPN rpn_proposals collect size directly propotional to the change of IMS_PER_BATCH:
    cfg.FPN.RPN_COLLECT_SCALE: 1.0
Number of data loading threads: 4
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train_net_step.py", line 457, in <module>
    main()
  File "tools/train_net_step.py", line 233, in main
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES)
  File "/home/xia/1-huafei/tianchi/xbu/Detectron.pytorch/lib/datasets/roidb.py", line 62, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/home/xia/1-huafei/tianchi/xbu/Detectron.pytorch/lib/datasets/roidb.py", line 62, in <listcomp>
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/home/xia/1-huafei/tianchi/xbu/Detectron.pytorch/lib/datasets/roidb.py", line 47, in get_roidb
    crowd_filter_thresh=cfg.TRAIN.CROWD_FILTER_THRESH
  File "/home/xia/1-huafei/tianchi/xbu/Detectron.pytorch/lib/datasets/json_dataset.py", line 152, in get_roidb
    self._add_gt_annotations(entry)
  File "/home/xia/1-huafei/tianchi/xbu/Detectron.pytorch/lib/datasets/json_dataset.py", line 224, in _add_gt_annotations
    if obj['area'] < cfg.TRAIN.GT_MIN_AREA:
TypeError: '<' not supported between instances of 'list' and 'int'

**Comment by HarrisXia** [comment]
thx for your kindness

**Comment by HarrisXia** [comment]
already done
