### ISSUE TITLE
Error when running test on one GPU when multiple are available.

### ISSUE THREAD

**Issue by Rizhiy** [roytseng-tw/Detectron.pytorch#23]
Hi, I tried to run a test today and got the following error:
```
Traceback (most recent call last):
  File "tools/test_net.py", line 108, in <module>
    check_expected_results=True)
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test_engine.py", line 158, in test_net_on_dataset
    args, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test_engine.py", line 253, in test_net
    cls_boxes_i, cls_segms_i, cls_keyps_i = im_detect_all(model, im, box_proposals, timers)
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, box_proposals)
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/core/test.py", line 127, in im_detect_bbox
    return_dict = model(**inputs)
  File "/home/rizhiy/miniconda3/envs/Detectron.pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/nn/parallel/data_parallel.py", line 82, in forward
    mini_kwargs = dict([(k, v[i]) for k, v in kwargs.items()])
  File "/home/rizhiy/object-detection/Detectron.pytorch/lib/nn/parallel/data_parallel.py", line 82, in <listcomp>
    mini_kwargs = dict([(k, v[i]) for k, v in kwargs.items()])
IndexError: list index out of range
```

The command I used to run the test: `python tools/test_net.py --cfg configs/e2e_mask_rcnn_R-101-FPN_2x.yaml --load_ckpt Outputs/e2e_mask_rcnn_R-101-FPN_2x/Apr19-11-34-35_devbox/ckpt/model_7_29315.pth --dataset coco2017`.

It appears that there is some inconsistency in the number of devices during setup.

Not sure what needs to be fixed, but as a workaround, you can just restrict python to one GPU with `CUDA_VISIBLE_DEVICES=0`.

**Comment by cherryxiongyw** [comment]
I have the same error when I run infer_simple.py

**Comment by roytseng-tw** [comment]
For using multi-gpu for testing, you have to manually specify `--multi-gpu-testing' in the command.
Otherwise, it assumes that you are going to use only one gpu.  Maybe I should improve the mechanism here.

**Comment by roytseng-tw** [comment]
Now it will raise an error if multiple gpus are available but `--multi-gpu-testing` is not specified, and vice versa.

**Comment by zimenglan-sysu-512** [comment]
hi @roytseng-tw ,
if i want one gpu to test the model when multi-gpus are available, how can i modify the code?
