### ISSUE TITLE
data_parallel error?

### ISSUE THREAD

**Issue by QiaoranC** [roytseng-tw/Detectron.pytorch#31]
Hi, thanks for contribution of mask rcnn, i like the ideal of building with different modules(you can try different backbone, box head, mask head), which has high potential for improvements. 
I try to using my customer dataset with coco style in this project. (Already successfully implemented in matterport's tf+keras mask rcnn)
But i get the following errors and get no clue.  
I guess it is something in the data_parallel?
Any suggestions/ideals are welcome.
```
Namespace(batch_size=2, cfg_file='/home/ubuntu/skin_demo/Tooth/Detection/configs/e2e_mask_rcnn_R-50-C4_1x.yaml', cuda=True, dataset='coco2014', disp_interval=20, load_ckpt=None, load_detectron=None, lr=None, lr_decay_gamma=None, no_save=False, num_workers=1, optimizer=None, resume=False, set_cfgs=[], start_step=0, use_tfboard=True)
Batch size change from 1 (in config file) to 2
NUM_GPUs: 1, TRAIN.IMS_PER_BATCH: 2
Number of data loading threads: 1
Adjust BASE_LR linearly according to batch size change: 0.01 --> 0.02
loading annotations into memory...
Done (t=0.26s)
creating index...
index created!
INFO json_dataset.py: 298: Loading cached gt_roidb from /home/ubuntu/skin_demo/Tooth/Detection/Detectron.pytorch-master/data/cache/coco_2014_train_gt_roidb.pkl
INFO roidb.py:  50: Appending horizontally-flipped training examples...
INFO roidb.py:  52: Loaded dataset: coco_2014_train
INFO roidb.py: 143: Filtered 0 roidb entries: 578 -> 578
INFO roidb.py:  69: Computing image aspect ratios and ordering the ratios...
INFO roidb.py:  71: done
INFO roidb.py:  75: Computing bounding-box regression targets...
INFO roidb.py:  77: done
INFO train_net_step.py: 203: 578 roidb entries
INFO train_net_step.py: 204: Takes 1.24 sec(s) to construct roidb
INFO train_net_step.py: 319: Training starts !
INFO net.py:  72: Changing learning rate 0.000000 -> 0.006667
Traceback (most recent call last):
  File "tools/train_net_step.py", line 397, in <module>
    main()
  File "tools/train_net_step.py", line 364, in main
    net_outputs = maskRCNN(**input_data)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/skin_demo/Tooth/Detection/Detectron.pytorch-master/lib/nn/parallel/data_parallel.py", line 113, in forward
    outputs = [self.module(*inputs[0], **kwargs[0])]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/skin_demo/Tooth/Detection/Detectron.pytorch-master/lib/modeling/model_builder.py", line 116, in forward
    roidb = list(map(lambda x: blob_utils.deserialize(x)[0], roidb))
  File "/home/ubuntu/skin_demo/Tooth/Detection/Detectron.pytorch-master/lib/modeling/model_builder.py", line 116, in <lambda>
    roidb = list(map(lambda x: blob_utils.deserialize(x)[0], roidb))
  File "/home/ubuntu/skin_demo/Tooth/Detection/Detectron.pytorch-master/lib/utils/blob.py", line 176, in deserialize
    return pickle.loads(arr.astype(np.uint8).tobytes())
AttributeError: 'list' object has no attribute 'astype'
```

**Comment by roytseng-tw** [comment]
What have you changed ? Just the paths to annotation file and directory of images ?

**Comment by QiaoranC** [comment]
Problem solved.
This time reclone the code and only change the paths to data, and everything works fine.
Cannot remember exactly whats changes in the early time.
