### ISSUE TITLE
Unpickling error while training from scratch e2e mask rcnn for Resnet-50-C4 (1x).

### ISSUE THREAD

**Issue by adiRpatgaonkar** [roytseng-tw/Detectron.pytorch#38]
**Conda 4.5, Python 3.6, Pytorch 0.3.1**
```
Traceback (most recent call last):
  File "tools/train_net_step.py", line 391, in <module>
    main()
  File "tools/train_net_step.py", line 222, in main
    maskRCNN = Generalized_RCNN()
mask-rcnn.pytorch/lib/modeling/model_builder.py", line 98, in __init__
    self._init_modules()
mask-rcnn.pytorch/lib/modeling/model_builder.py", line 102, in _init_modules
    resnet_utils.load_pretrained_imagenet_weights(self)
/mask-rcnn.pytorch/lib/utils/resnet_weights_helper.py", line 21, in load_pretrained_imagenet_weights
    pretrianed_state_dict = convert_state_dict(torch.load(weights_file))
lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
lib/python3.6/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
```
What am I missing?
Please help.

**Comment by roytseng-tw** [comment]
Are you having the correct imagenet pretrained weights ?

**Comment by adiRpatgaonkar** [comment]
Yes, I presume. I have used the script `tools/download_imagenet_weights.py`  to download the pretrained model. I have tried downloading twice. Still gives me the same error. What am I missing?

**Comment by adiRpatgaonkar** [comment]
I erroneously closed the issue. Any solution?

**Comment by roytseng-tw** [comment]
Have you try loading the weight in ipython/python ?

**Comment by adiRpatgaonkar** [comment]
Yes, I did try that from within the python interpreter too. Same error.

**Comment by roytseng-tw** [comment]
You may try downloading the file through your browser, and load the file again.

**Comment by adiRpatgaonkar** [comment]
I guess you are right. It works! Thank you :)
