### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_bbox)

### ISSUE THREAD

**Issue by KaiyuYue** [roytseng-tw/Detectron.pytorch#49]
Hi, @roytseng-tw 
I encounter the import problems (`python3.5`), need help. Thanks.

```bash
$ python3 tools/train_net_step.py --dataset coco2017 --cfg configs/e2e_mask_rcnn_R-50-C4.yml --use_tfboard --bs 4 --nw 4

Traceback (most recent call last):
  File "tools/train_net_step.py", line 25, in <module>
    from datasets.roidb import combined_roidb_for_training
  File "/home/yuekaiyu/code/Detectron.pytorch/lib/datasets/roidb.py", line 27, in <module>
    import utils.boxes as box_utils
  File "/home/yuekaiyu/code/Detectron.pytorch/lib/utils/boxes.py", line 52, in <module>
    import utils.bbox as cython_bbox
ImportError: dynamic module does not define module export function (PyInit_bbox)
```

**Comment by Pirazh** [comment]
Hi @KaiyuYue , 

were you be able to find the solution to this problem? I am having similar issue currently.

Thanks

**Comment by Pirazh** [comment]
I figured it out, the solution that worked for me was to make sure the  `{root_dir}/lib/setup.py`  is run by python3, also the names of .pyx files in the `{root_dir}/lib/utils` directory should be the same as the ones in the setup.py
