### ISSUE TITLE
Problem with building/installing extensions in lib

### ISSUE THREAD

**Issue by phalexo** [roytseng-tw/Detectron.pytorch#80]
cd lib
sh make.sh
# appears unable to find TH.h and THC.h 

gcc -pthread -B /home/developer/anaconda3/envs/pytorch/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/developer/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/developer/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/developer/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/developer/anaconda3/envs/pytorch/include/python3.5m -c /home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c -o ./home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.o -std=c99
/home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c: In function 'nms_cuda':
/home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c:14:22: error: dereferencing pointer to incomplete type
            boxes_host->size[0],
                      ^
/home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c:15:22: error: dereferencing pointer to incomplete type
            boxes_host->size[1],
                      ^
Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

The command that you ran
```

### System information

* Operating system: ?
Ubuntu 14.04
* CUDA version: ?
9.1
* cuDNN version: ?
7.1.3
* GPU models (for all devices if they are not all the same): ?
Maxwell Titan X
* python version: ?
3.5 under anaconda3
* pytorch version: ?
latest from github, 0.0.5 
* Anything else that seems relevant: ?

**Comment by phalexo** [comment]
gcc -pthread -B /home/developer/anaconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/developer/anaconda3/envs/pytorch/include/python3.6m -c /home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c -o ./home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.o -std=c99
/home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c: In function 'nms_cuda':
/home/developer/Detectron.pytorch/lib/model/nms/src/nms_cuda.c:14:22: error: dereferencing pointer to incomplete type 'THCTensor {aka struct THCTensor}'
            boxes_host->size[0],
                      ^
Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...

**Comment by stoneyang** [comment]
See [here](https://github.com/pytorch/pytorch/issues/8483).
