### ISSUE TITLE
Multiple reports of problems with "sh make.sh" building.

### ISSUE THREAD

**Issue by phalexo** [roytseng-tw/Detectron.pytorch#87]
It appears that in most case reported, the script is unable to locate some resource. 

What should PYTHONPATH be, for example, to find appropriate files in pytorch, etc...?

**Comment by phalexo** [comment]
(pytorch) developer@theano:~/Detectron.pytorch$ python tools/train_net_step.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_R-50-C4.yml --use_tfboard --bs 128 --nw 16
Traceback (most recent call last):
  File "tools/train_net_step.py", line 27, in <module>
    from modeling.model_builder import Generalized_RCNN
  File "/home/developer/Detectron.pytorch/lib/modeling/model_builder.py", line 12, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/developer/Detectron.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/developer/Detectron.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'model.roi_crop._ext.roi_crop._roi_crop'

**Comment by phalexo** [comment]
Pytorch source was changed. Have to use functuons to get sizes instead of ->
