### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by JudyYe** [roytseng-tw/Detectron.pytorch#88]
Hi, when I run the benchmark
```
python tools/train_net_step.py \
  --dataset coco2017 --cfg configs/e2e_faster_rcnn_R-50-FPN_1x.yaml \
  --bs 8 --iter_size 2 --use_tfboard
```, I got the error:
```
Traceback (most recent call last):
  File "tools/train_net_step.py", line 22, in <module>
    import utils.net as net_utils
  File "/home/yufeiy2/Detectron.pytorch/lib/utils/net.py", line 12, in <module>
    logger = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'
```

It seems that in net.py, the script import logging under `lib/utils/logging.py`, but should import logging from python site-packages.

any idea to solve it?

Thank you.

**Comment by enderhsu** [comment]
you may need to rename lib/utils/logging.py to other name. Also modify "import utils.logging" if necessary.

**Comment by dangkhoasdc** [comment]
Renaming the logging.py actually is not a solution, I changed the file and later I have to change `collections.py` and other code.

I solved this issuse by re-compiling the lib by python3.

**Comment by hbwx24** [comment]
I also encontered this problem,and I use python2.7. should I change python version？

**Comment by dangkhoasdc** [comment]
@hbwx24  yes, it indeed solved the problem.

**Comment by HongwenZhang** [comment]
Adding `from __future__ import absolute_import` at head of train_net_step.py could solve this problem.

**Comment by Z0org** [comment]
I still get the same problem with python 3.5.4 (and 2.7.2) torch 0.4.0, torchvision 0.2.0 and cuda 9.0 on ubuntu 16.04. 
When I try `from __future__ import absolute_import` I still get the error.

**Comment by 13070151771** [comment]
me too.it doesnt work~

**Comment by Wapiti08** [comment]
> Renaming the logging.py actually is not a solution, I changed the file and later I have to change `collections.py` and other code.
> 
> I solved this issuse by re-compiling the lib by python3.

How could you re-compiling the lib? Can you send me the script?

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/usr/lib/python3/dist-packages/apt/package.py", line 24, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

Original exception was:
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'
kidly help me to resolve this issue i have been using tensorflow 1.14 GPU based

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/usr/lib/python3/dist-packages/apt/package.py", line 24, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

Original exception was:
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'
kindly help me to resolve this issue I am using tensorflow 2.0.0

**Comment by haardikdharma10** [comment]
Any fix yet??
